version: "3.7"

services:
  app:
    image: status-page-check:latest
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
  redis: 
    image: redis:5.0

